#!/bin/bash
#
#$ -cwd
#$ -j y
#$ -S /bin/bash
#

OUTDIR="/nfs/apollo/2/c2b2/users/saec/SJS/usr/ys/data/Genotypes/"
MAP="/nfs/apollo/2/c2b2/users/saec/SJS/usr/ys/data/mapping_info.txt"
PROG="/nfs/apollo/2/c2b2/users/saec/SJS/usr/ys/perl/extractPatients.pl"

date

perl $PROG -outfile test.out -outdir $OUTDIR -infile "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12277-DNA.csv" -map $MAP

perl $PROG -outfile test.out -outdir $OUTDIR -infile "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12914-DNA.csv" -map $MAP


perl $PROG -outfile test.out -outdir $OUTDIR -infile "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_12278-DNA.csv" -map $MAP

perl $PROG -outfile test.out -outdir $OUTDIR -infile "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12276-DNA.csv" -map $MAP

#gawk -f ~/SJS/scripts/extractIndividuals.awk "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12277-DNA.csv"
# gawk -f ~/SJS/scripts/extractIndividuals.awk "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12914-DNA.csv"
#gawk -f ~/SJS/scripts/extractIndividuals.awk "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_12278-DNA.csv"
# gawk -f ~/SJS/scripts/extractIndividuals.awk "/nfs/apollo/2/c2b2/users/saec/SJS/uploads/SJS-Oct-11-2007/SJS_Delivery_from_GSK/PGX40001_Illumina1M/Extracted Genotypes/PGx40001_GSK_SJS_B137_28Aug2007_Genotype_Report_12276-DNA.csv"


date

