#!/bin/bash
#
#$ -cwd
#$ -j y
#$ -S /bin/bash
#
 
date

scriptDir="/nfs/apollo/2/c2b2/users/saec/SJS/usr/ys/shell/"
dataDir="/nfs/apollo/2/c2b2/users/saec/SJS/usr/ys/data/fromBernd/"
# plinkCMD="/nfs/apollo/1/shares/software/core_facility/local/x86_64_rocks/plink/plink-0.99s-x86_64/plink"
plinkCMD="/nfs/apollo/2/c2b2/users/saec/Software/plink-1.02-x86_64/plink"
fpName="whitesR1HapMapCEU"


## WHITES
#remove Individuals
$plinkCMD --bfile ${dataDir}/whitesHMR1    --out ${dataDir}/${fpName}  --remove ${dataDir}/whitesHMR1.fam.HapMapID_nonCEU.remove  --make-bed

# remove SNPs
$plinkCMD --bfile ${dataDir}/${fpName} --out ${dataDir}/${fpName}  --missing --hardy
gawk '{if(NR>1)if(($6+0)<5*10^-8)print $1}'  ${dataDir}/${fpName}.hwe     > ${dataDir}/removeSNPsWhites-R1.txt
gawk '{if(NR>1)if(($4+0)>0.05) print   $2}'  ${dataDir}/${fpName}.lmiss  >> ${dataDir}/removeSNPsWhites-R1.txt
wc ${dataDir}/removeSNPsWhites-R1.txt
$plinkCMD --bfile ${dataDir}/${fpName}    --out ${dataDir}/${fpName}  --exclude  ${dataDir}/removeSNPsWhites-R1.txt  --make-bed

# ${plinkCMD} --bfile /nfs/apollo/2/c2b2/users/saec/SJS/usr/bernd/data/${fpName} --out /nfs/apollo/2/c2b2/users/saec/SJS/usr/bernd/data/${fpName}  --recode
date
